config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/', to: 'pages#home'
  get '/about', to: 'pages#about'
  get '/dashboard', to: 'pages#dashboard'
  get '/kita-finder', to: 'pages#kita_finder'
  get '/kitas', to: 'pages#kitas'
  get '/lexicon', to: 'pages#lexicon'
  get '/midwife-system', to: 'pages#midwives'
  get '/paternity-acknowledgment', to: 'pages#paternity_acknowledgment'
  root to: 'pages#home'

  resources :kindergartens, only: [:index, :show] do
    resources :kita_contacts, only: [ :new, :create ]
    resources :kita_reminders, only: [:new, :create]
  end

  resources :kita_contacts, only: [:index, :update, :destroy]
  resources :kita_reminders, only: [:destroy]
end

app/models/kindergarten.rb
class Kindergarten < ApplicationRecord
  has_many :kita_contacts
  has_many :kita_reminders

  geocoded_by :address

  def num_reminders(current_user)
    kita_reminders.count_reminders(current_user)
  end

  def any_reminder_today?(current_user)
    kita_reminders.any_today?(current_user)
  end
end

app/controllers/kindergartens_controller.rb
class KindergartensController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def get_minimum_age
    return @kindergartens = @kindergartens if params[:minimum_age] == 'all'
    @kindergartens = @kindergartens.where('minimum_age <= ?', params[:minimum_age])
  end

  def get_places
    case params[:places]
    when 'all'
      @kindergartens = @kindergartens
    when '< 20'
      @kindergartens = @kindergartens.where('places < ?', 20)
    when '20 - 50'
      @kindergartens = @kindergartens.where('places >= ?', 20).where('places < ?', 50)
    when '50 - 100'
      @kindergartens = @kindergartens.where('places >= ?', 50).where('places < ?', 100)
    when '> 100'
      @kindergartens = @kindergartens.where('places >= 100', 6)
    end
  end

  def index
    if params[:address].present?
      address = params[:address] + " Berlin"
      params[:radius].present? ? radius = params[:radius] : radius = 2
      @kindergartens = Kindergarten.near(address, radius)
      get_minimum_age
      get_places
    else
      @kindergartens = Kindergarten.where.not(latitude: nil, longitude: nil)
    end
    @markers = @kindergartens.map do |kindergarten|
      {
        details: {
          contacts: kindergarten.kita_contacts.where(user: current_user)
        },
        lng: kindergarten.longitude,
        lat: kindergarten.latitude,
        infoWindow: render_to_string(partial: "infowindow", locals: { kindergarten: kindergarten })
      }
    end
  end

  def show
    @kindergarten = Kindergarten.find(params[:id])
    @kita_contacts = @kindergarten.kita_contacts.where(user: current_user).order(created_at: :desc)
    @kita_contact = KitaContact.new
    @kita_reminder = KitaReminder.new
    @markers = [{
      details: {
        contacts: @kindergarten.kita_contacts.where(user: current_user)
      },
      lng: @kindergarten.longitude,
      lat: @kindergarten.latitude,
      infoWindow: render_to_string(partial: "infowindow", locals: { kindergarten: @kindergarten })
    }]
  end
end

app/views/kindergartens/_infowindow.html.erb
<% if kindergarten.kita_contacts.where(user: current_user).empty? %>
  <p class="font-dark-blue"><strong><%= kindergarten.name %></strong></p>
<% else %>
  <p class="font-pink"><strong><%= kindergarten.name %></strong></p>
<% end %>

<p class="mb-3"><%= kindergarten.address %></p>

<% unless @kindergarten %>
  <p><%= link_to 'More details', kindergarten_path(kindergarten), target: "_blank", class:"btn-pib-dark btn-short" %></p>
<% end %>

app/views/kindergartens/index.html.erb
<% content_for :meta_title, "Kita map - #{DEFAULT_META["meta_product_name"]}" %>

<div class="window d-block d-sm-flex">
  <div class="search-container d-none d-sm-block">
    <div class="search-title">
      <h2>Kita Finder</h2>
    </div>

    <div class="form-container">
      <%= form_tag kindergartens_path, method: :get do %>
        <%= text_field_tag :address,
          params[:address],
          class: "form-control",
          placeholder: "What's your address?"
        %>
        <p><button class="btn btn-pib mt-2 btn-short" type="button" data-toggle="collapse" data-target="#collapseSearch" aria-expanded="false" aria-controls="collapseExample">
          Additional filter options
        </button></p>
        <div class="collapse" id="collapseSearch">
          <p>Search radius (in km):</p>
          <%= select_tag :radius, options_for_select([1, 2, 5, 10, 20, 30], params[:radius]), class:"form-control" %>

          <p>Minimum age (in months):</p>
          <%= select_tag :minimum_age, options_for_select(["all", 6, 12, 18], params[:minimum_age]),class:"form-control" %>

          <p>Kita size (in nb of total kids)</p>
          <%= select_tag :places, options_for_select(["all", "< 20", "20 - 50", "50 - 100", "> 100"], params[:places]), class:"form-control" %>
        </div>

        <%= submit_tag "Search", class: "btn-pib-dark mt-2" %>
      <% end %>
    </div>
  </div>

  <div class="search-container-small d-block d-sm-none">
    <div class="search-title">
      <h3>Kita Finder</h3>
    </div>

    <div class="form-container">
      <%= form_tag kindergartens_path, method: :get do %>
        <%= text_field_tag :address,
          params[:address],
          class: "form-control d-inline",
          placeholder: "What's your address?"
        %>
        <div class="dropdown d-inline">
          <button class="btn-pib d-inline dropdown-toggle" type="button" id="dropdownSearchButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Filter
          </button>
          <div class="dropdown-menu pl-2" aria-labelledby="dropdownSearchButton">
            <div>Search radius (in km):</div>
            <%= select_tag :radius, options_for_select([1, 2, 5, 10, 20, 30], params[:radius]), class:"form-control" %>

            <div>Minimum age (in months):</div>
            <%= select_tag :minimum_age, options_for_select(["all", 6, 12, 18], params[:minimum_age]), class:"form-control" %>

            <div>Kita size (in nb of total kids)</div>
            <%= select_tag :places, options_for_select(["all", "< 20", "20 - 50", "50 - 100", "> 100"], params[:places]), class:"form-control" %>
          </div>
        </div>

        <%= submit_tag "Go", class: "btn-pib-dark d-inline" %>
      <% end %>
    </div>
  </div>

  <div
    id="map"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
  ></div>
</div>

app/views/kindergartens/show.html.erb
<% content_for :meta_title, "#{@kindergarten.name} - #{DEFAULT_META["meta_product_name"]}" %>

<div class="container">
  <div class="static-container">
    <h1 class="pt-3"><%= @kindergarten.name %></h1>

    <div class="d-block d-sm-flex">
      <div class="kita-details">

        <div class="kita-details-contacts">
          <p><i class="fas fa-map-marker-alt"></i> <%= @kindergarten.address %></p>
          <p><i class="fas fa-phone"></i> <%= @kindergarten.phone_number %></p>
          <% unless @kindergarten.email == "" %>
            <p><i class="far fa-envelope"></i> <%= link_to @kindergarten.email, "mailto:".concat(@kindergarten.email), class:"pib-text-link" %></p>
          <% end %>
          <% unless @kindergarten.url == "" %>
            <% if @kindergarten.url.start_with?("www") %>
              <p><i class="fas fa-angle-double-right"></i> <%= link_to 'Go to website', "http://".concat(@kindergarten.url), class:"pib-text-link", target:"_blank" %></p>
            <% else %>
              <p><i class="fas fa-angle-double-right"></i> <%= link_to 'Go to website', @kindergarten.url, class:"pib-text-link", target:"_blank" %></p>
            <% end %>
          <% end %>
        </div>

        <div class="d-none d-sm-block">

          <div class="d-flex">
            <div class="col-sm-4 pl-0">Minimum age: </div>
            <div class="col-sm-5"><%= @kindergarten.minimum_age %> months old</div>
          </div class="d-flex">
          <div class="d-flex border-top">
            <div class="col-sm-4 pl-0">Total places: </div>
            <div class="col-sm-5"><%= @kindergarten.places %></div>
          </div class="d-flex">
          <div class="d-flex border-top">
            <div class="col-sm-4 pl-0">Total places under 3 y.o.: </div>
            <div class="col-sm-5"><%= @kindergarten.places_under_three %></div>
          </div class="d-flex">
          <div class="d-flex border-top">
            <div class="col-sm-4 pl-0">Total places over 3 y.o.: </div>
            <div class="col-sm-5"><%= @kindergarten.places_over_three %></div>
          </div class="d-flex">

          <% unless @kindergarten.open_time_mon.nil? %>
            <p class="border-top">Opening times:</p>
            <div class="opening-times">
              <div class="d-flex">
                <div class="col-sm-2 text-center">Mon</div>
                <div class="col-sm-2 text-center">Tue</div>
                <div class="col-sm-2 text-center">Wed</div>
                <div class="col-sm-2 text-center">Thu</div>
                <div class="col-sm-2 text-center">Fri</div>
              </div>
              <div class="d-flex">
                <div class="col-sm-2 pr-5"><%= @kindergarten.open_time_mon %></div>
                <div class="col-sm-2 pr-5"><%= @kindergarten.open_time_tue %></div>
                <div class="col-sm-2 pr-5"><%= @kindergarten.open_time_wed %></div>
                <div class="col-sm-2 pr-5"><%= @kindergarten.open_time_thu %></div>
                <div class="col-sm-2 pr-5"><%= @kindergarten.open_time_fri %></div>
              </div>
            </div>
          <% end %>

        </div>

        <div class="d-block d-sm-none">
          <p>
            <a class="btn btn-pib mt-1 btn-short" data-toggle="collapse" href="#collapseKitaDetails" aria-expanded="false" role="button" aria-controls="collapseKitaDetails">More details about the kita</a>
          </p>
          <div class="collapse" id="collapseKitaDetails">

              <div class="d-flex">
                <div class="col-sm-4 pl-0">Minimum age: </div>
                <div class="col-sm-5 text-center"><%= @kindergarten.minimum_age %> months old</div>
              </div>
              <div class="d-flex border-top">
                <div class="col-sm-4 pl-0">Total places: </div>
                <div class="col-sm-5 text-center"><%= @kindergarten.places %></div>
              </div>
              <div class="d-flex border-top">
                <div class="col-sm-4 pl-0">Total places under 3 y.o.: </div>
                <div class="col-sm-5 my-auto text-center"><%= @kindergarten.places_under_three %></div>
              </div>
              <div class="d-flex border-top">
                <div class="col-sm-4 pl-0">Total places over 3 y.o.: </div>
                <div class="col-sm-5 my-auto text-center"><%= @kindergarten.places_over_three %></div>
              </div>

              <% unless @kindergarten.open_time_mon.nil? %>
                <div class="border-top">Opening times:</div>

                <div class="opening-times">
                  <div class="d-flex">
                    <div class="col-sm-4 pl-0">Mon</div>
                    <div class="col-sm-5"><%= @kindergarten.open_time_mon %></div>
                  </div>
                  <div class="d-flex">
                    <div class="col-sm-4 pl-0">Tue</div>
                    <div class="col-sm-5"><%= @kindergarten.open_time_tue %></div>
                  </div>
                  <div class="d-flex">
                    <div class="col-sm-4 pl-0">Wed</div>
                    <div class="col-sm-5"><%= @kindergarten.open_time_wed %></div>
                  </div>
                  <div class="d-flex">
                    <div class="col-sm-4 pl-0">Thu</div>
                    <div class="col-sm-5"><%= @kindergarten.open_time_thu %></div>
                  </div>
                  <div class="d-flex">
                    <div class="col-sm-4 pl-0">Fri</div>
                    <div class="col-sm-5"><%= @kindergarten.open_time_fri %></div>
                  </div>
                </div>
              <% end %>

          </div>
        </div>
      </div>

      <div class="map-container">
        <div
          id="map"
          style="width: 100%;
          height: 100%;"
          class="kita-show-map"
          data-markers="<%= @markers.to_json %>"
          data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
        ></div>
      </div>
    </div>

    <div class="mt-5">
      <h4>Contact history with <%= @kindergarten.name %></h4>

      <% @kita_contacts.each_with_index do |kita_contact, i| %>
        <div class="d-flex justify-content-between mt-1">
          <div class="kita-contacts d-flex">
            <div class="kita-contacts-item col-sm-1 text-center">
              <% if kita_contact.contact_type == "call" %>
                <i class="fas fa-phone"></i>
              <% elsif kita_contact.contact_type == "email" %>
                <i class="fas fa-at"></i>
              <% elsif kita_contact.contact_type == "visit" %>
                <i class="fas fa-walking"></i>
              <% elsif kita_contact.contact_type == "other" %>
                <i class="fas fa-th-list"></i>
              <% end %>
            </div>
            <div class="kita-contacts-item kita-contacts-date col-sm-3">
              <%= kita_contact.created_at.strftime("%a %e %B - %H:%M") %>
            </div>
            <div class="kita-contacts-item col-sm-8">
              <%= kita_contact.note %>
            </div>
          </div>
          <div class="d-flex my-auto" style:"width: 50px;">
            <div>
              <a class='btn-icon btn-dark' role="button" data-toggle="collapse" href="#collapseEdit<%= i %>" aria-expanded="false" aria-controls="collapseEdit<%= i %>">
                <i class="fas fa-edit"></i>
              </a>
            </div>

            <div>
              <%= link_to kita_contact_path(kita_contact),
              method: :delete,
              data: { confirm: "Are you sure?" }, class:'btn-icon btn-pink' do %>
                <i class="fas fa-trash-alt"></i>
              <% end %>
            </div>
          </div>
        </div>
        <div class="collapse" id="collapseEdit<%= i %>">
          <%= simple_form_for kita_contact, :url => kita_contact_path(kita_contact), :method => :patch do |f| %>
              <div class="form-inline form-new-contact">
                <div class="form-group">
                  <%= f.input :contact_type,
                  collection: %w(call email visit other),
                  input_html: { class: "form-control" },
                  label: false %>
                  <%= f.input :created_at, as: :string, input_html: { class: "form-control datepicker-update" }, label: false %>
                  <%= f.input :note, input_html: { style: 'height:40px;', class: "form-control",
                    placeholder: 'Add a note',
                    rows: 1 },
                  label: false %>
                </div>
                <%= f.submit "Edit", class: "m-auto btn-pib-dark btn-short" %>
              </div>
            <% end %>
        </div>
      <% end %>

      <div class="my-4">
        <h5>Add a new contact:</h5>

        <% if current_user %>

          <%= render "kita_contacts/new" %>

          <h5 class="mt-4">Add a reminder:</h5>
          <%= render "kita_reminders/new" %>

        <% else %>

          <p class="font-dark-blue">Log in or Sign up to be able to add notes about your contact history</p>

          <%= link_to "Log in", new_user_session_path, class: "btn-pib" %>
          <%= link_to "Sign up", new_user_registration_path, class: "btn-pib" %>

        <% end %>
      </div>

    </div>
  </div>
</div>