config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/', to: 'pages#home'
  get '/about', to: 'pages#about'
  get '/dashboard', to: 'pages#dashboard'
  get '/kita-finder', to: 'pages#kita_finder'
  get '/kitas', to: 'pages#kitas'
  get '/lexicon', to: 'pages#lexicon'
  get '/midwife-system', to: 'pages#midwives'
  get '/paternity-acknowledgment', to: 'pages#paternity_acknowledgment'
  root to: 'pages#home'

  resources :kindergartens, only: [:index, :show] do
    resources :kita_contacts, only: [ :new, :create ]
    resources :kita_reminders, only: [:new, :create]
  end

  resources :kita_contacts, only: [:index, :update, :destroy]
  resources :kita_reminders, only: [:destroy]
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible alert-pib" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-warning alert-dismissible alert-pib" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer-box">
  <div class="ml-4">
    <%= link_to "About PiB", about_path, class: "pib-text-link-light" %> |
    <%= link_to "Lexicon", lexicon_path, class: "pib-text-link-light" %>
  </div>
  <p class="mr-4">Created in 2019</p>
</div>

app/views/shared/_navbar.html.erb
<% unless current_user %>

  <div class="navbar navbar-dark navbar-lewagon">
    <%= link_to root_path, class: "navbar-brand" do %>
      <i class="fas fa-baby"> <span class="pib-font">Pregnant in Berlin</span></i>
    <% end %>
    <div>
      <%= link_to "Log in", new_user_session_path, class: "btn-pib-dark" %>
    </div>
  </div>

<% else %>

  <div class="navbar navbar-dark navbar-lewagon">
    <%= link_to "/", class: "navbar-brand" do %>
      <i class="fas fa-baby"> <span class="pib-font">Pregnant in Berlin</span></i>
    <% end %>

    <div class="navbar-links">

      <div class="d-flex">
        <%= link_to "Dashboard", "/dashboard" %>
        <% if KitaReminder.any_today?(current_user) %>
          <div class="navbar-badge">#</div>
        <% end %>
      </div>

      <%= link_to "", destroy_user_session_path, method: :delete, class: "fas fa-sign-out-alt" %>

    </div>
  </div>

<% end %>