config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/', to: 'pages#home'
  get '/about', to: 'pages#about'
  get '/dashboard', to: 'pages#dashboard'
  get '/kita-finder', to: 'pages#kita_finder'
  get '/kitas', to: 'pages#kitas'
  get '/lexicon', to: 'pages#lexicon'
  get '/midwife-system', to: 'pages#midwives'
  get '/paternity-acknowledgment', to: 'pages#paternity_acknowledgment'
  root to: 'pages#home'

  resources :kindergartens, only: [:index, :show] do
    resources :kita_contacts, only: [ :new, :create ]
    resources :kita_reminders, only: [:new, :create]
  end

  resources :kita_contacts, only: [:index, :update, :destroy]
  resources :kita_reminders, only: [:destroy]
end

app/views/pages/_infowindow.html.erb
<p class="kita-contacts-infowindow"><strong><%= kindergarten.name %></strong></p>

app/views/pages/about.html.erb
<% content_for :meta_title, "About us - #{DEFAULT_META["meta_product_name"]}" %>

<div class="container">
  <div class="static-container pages-container">
    <h1 class="font-dark-blue">What is Pregnant in Berlin?</h1>
    <p><%= link_to "Pregnant in Berlin", root_path, class: "pib-text-link" %>'s first aim is to help foreign couples expecting a child to find their way in the German system concerning pregnancy and child care.</p>
    <p>Germany offers a lot of help to future parents, but navigating through the administration can prove difficult for foreigners. This is the main reason why this website was created: giving an overview of all the services that families can benefit from.</p>

    <h1 class="font-dark-blue">Who's behind Pregnant in Berlin?</h1>
    <p>I'm a French web developer who arrived in Berlin in 2016. 3 years later, I got pregnant and I quickly realized I was at a loss when it came to understanding how the German system works.</p>
    <p>Sure, there are some things that were very similar to France, for instance: go see your gynecologist as soon as your pregnancy test tells you you're pregnant. But midwives do not play such an important role so early in the pregnancy as they do in Germany. Meaning that when I started looking for one when I was 4 months pregnant, I was often told it was too late and all were fully booked!</p>
    <p>And I haven't started talking about the German administration. Parental leave and the amount of money you receive from it is extremely different from the way it works in France, and looking into it proved hard especially when the language isn't my native one.</p>
    <p>This is the reason why I decided during my maternity leave to create the website I wish I had had access to from the start. A website focused on Berlin that regroups all aspects of a pregnancy, may they be administrative, medical or other, that could help other parents that are in a similar situation as mine. I hope <span class="pib-text-link">Pregnant in Berlin</span> will reach its goal and can help you during this extraordinary moment that you are currently experiencing :)</p>
  </div>
</div>

app/views/pages/dashboard.html.erb
<% content_for :meta_title, "Dashboard - #{DEFAULT_META["meta_product_name"]}" %>
<div class="container">
  <div class="static-container">
    <% unless current_user %>

      <div class="col-md-8 m-auto text-center">
        <h3 class="my-5">Please log in to be able to access your dashboard!</h3>
        <%= link_to "Log in", new_user_session_path, class: "btn-pib" %>
      </div>

    <% else %>

      <h1>All my kita contacts</h1>

      <!-- displaying reminders if any -->

      <% if @kita_reminders.any? %>
        <div class="mb-3">

          <button class="btn btn-pib-pink mb-2" type="button" data-toggle="collapse" data-target="#collapseReminders" aria-expanded="false" aria-controls="collapseReminders">
            Reminders
          </button>

          <div class="collapse" id="collapseReminders">
            <% @kita_reminders.each do |kr| %>
              <div class="kita-reminder-entry">
                <h4>
                  <% if kr.today? %>
                    <span class="font-pink"><%= kr.count_down %></span>
                  <% else %>
                    <span class="font-dark-blue"><%= kr.count_down %></span>
                  <% end %>
                  - <%= kr.date.strftime("%a %e %B - %H:%M") %></h4>
                <div class="entry-title"><%= kr.title %> | <i><%= kr.kindergarten.name %></i></div>
                <div class="entry-content"><%= kr.content %></div>
              </div>
            <% end %>
          </div>


        </div>
      <% end %>

      <!-- displaying kita contacts if any -->

      <% if @kitas.empty? %>

        <p class="pt-5 text-center"><i>You don't have any kita details for the moment. Check our Kita Finder to help you locate your ideal kita!</i></p>

        <%= link_to "Go to Kita Finder", kita_finder_path, class:"btn-pib-dark d-block mx-auto text-center", style:"width: 160px;" %>

      <% else %>
        <div
          id="map"
          class="kita-contacts-map"
          data-markers="<%= @markers.to_json %>"
          data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
        ></div>

        <% @kitas.each do |k| %>
          <div class="my-4">
            <div class="d-flex">
              <h3><%= link_to k.name, kindergarten_path(k), class: "pib-text-link" %></h3>
              <% if k.any_reminder_today?(current_user) %>
                <div class="reminder-badge reminder-badge-pink" data-toggle="tooltip" data-placement="bottom" title="You have a reminder for today!">
                  <%= k.num_reminders(current_user) %>
                </div>
              <% elsif k.num_reminders(current_user) > 0 %>
                <div class="reminder-badge reminder-badge-dark-blue" data-toggle="tooltip" data-placement="bottom" title="Reminders">
                  <%= k.num_reminders(current_user) %>
                </div>
              <% end %>
            </div>
            <% k.kita_contacts.where(user: current_user).order(created_at: :desc).each do |kc| %>
              <div class="kita-contacts d-flex">
                <div class="kita-contacts-item col-sm-1 text-center">
                  <% if kc.contact_type == "call" %>
                    <i class="fas fa-phone"></i>
                  <% elsif kc.contact_type == "email" %>
                    <i class="fas fa-at"></i>
                  <% elsif kc.contact_type == "visit" %>
                    <i class="fas fa-walking"></i>
                  <% elsif kc.contact_type == "other" %>
                    <i class="fas fa-th-list"></i>
                  <% end %>
                </div>
                <div class="kita-contacts-item col-sm-2">
                  <%= kc.created_at.strftime("%a %e %B - %H:%M") %>
                </div>
                <div class="kita-contacts-item col-sm-9">
                  <%= kc.note %>
                </div>
              </div>
            <% end %>
          </div>
        <% end %>

      <% end %>

    <% end %>
  </div>
</div>

app/views/pages/kita_finder.html.erb
<% content_for :meta_title, "Kita Finder - #{DEFAULT_META["meta_product_name"]}" %>

<div class="container">
  <div class="static-container kita-finder-container">
    <h1 class="text-center py-5" style="font-size: 60px;">Kita Finder</h1>
    <p class="mb-5 d-block mx-auto">Our Kita Finder will help you locate all kitas around your home. Enter your preferences below, click on "Search" and start your hunt for the perfect kita!</p>

    <div class="kita-finder-form form-container offset-sm-3 col-sm-6 border rounded-sm mb-3">
      <%= form_tag kindergartens_path, method: :get, class:"mb-3" do %>
        <%= text_field_tag :address,
          params[:address],
          class: "form-control mt-3",
          placeholder: "What's your address?"
        %>

        <p>Search radius (in km):</p>
        <%= select_tag :radius, options_for_select([1, 2, 5, 10, 20, 30]), class:"form-control" %>

        <p>Minimum age (in months):</p>
        <%= select_tag :minimum_age, options_for_select(["all", 6, 12, 18]),class:"form-control" %>

        <p>Kita size (in nb of total kids)</p>
        <%= select_tag :places,
          "<option>all</option>
          <option>< 20</option>
          <option>20 - 50</option>
          <option>50 - 100</option>
          <option>> 100</option>". html_safe, class:"form-control" %>

        <%= submit_tag "Search", class: "btn-pib-dark d-block mt-3 mx-auto", style: "width: 120px;" %>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/kitas.html.erb
<% content_for :meta_title, "Kita system - #{DEFAULT_META["meta_product_name"]}" %>

<div class="container">
  <div class="static-container pages-container">
    <h1>Understanding the German kita system</h1>

    <h2>What is a kita?</h2>
    <p>In Germany, school starts at the age of 6. If parents are looking for children day care before their children reach that age, the most frequent solution are the <i>Kindertagesstätte</i>, more commonly known as kitas.</p>
    <p>Each kita is divided into two parts. The first one is the <strong>Kinderkrippe</strong> and takes care of children below the age of 3. Even if many kitas claim to accept children as young as 8 weeks old on their website, most of them are reluctant to have small babies and prefer to have children that are at least 1 year old. For children between the age of 3 and 6, the <strong>Kindergarten</strong> is where they will be cared for.</p>
    <p>Kitas come in all shapes and forms and parents should pay attention to certain elements before applying. For instance, each kita puts an <strong>emphasis on different aspects of education</strong>, among which are: languages (some kitas are officially bilingual or even multilingual), religion, diet (vegetarian, organic...), integration, nature and so much more. Some also follow a certain educational concept such as Montessori or Waldorf.</p>

    <div class="box-pib">
      <h3>Kita finder</h3>
      <p>The <strong>Kita Finder</strong> is a tool that allows you to check the kitas in your area and lets you add notes and comments about the kitas you have contacted.</p>
      <%= link_to "Kita Finder", kita_finder_path, class:"btn-pib-dark d-block mx-auto text-center", style:"width: 125px;" %>
    </div>

    <h2>The Kita Gutschein</h2>
    <p>German states all have different regulations concerning children day care. Berlin offers a <strong>free day care system</strong> from which parents can benefit through a <i>Gutschein</i> (voucher). This Gutschein can be valid for <i>Halbstags</i> (4 to 5 hours a day), <i>Teilzeit</i> (5 to 7 hours a day), <i>Ganztags</i> (7 to 9 hours a day) or <i>Erweitere Ganztags</i> (more than 9 hours a day) depending on your situation.</p>
    <p>Do note that even though kitas are free in Berlin, you will usually have to <strong>pay a monthly fee that covers lunch</strong> (around 23€ per month). You might also have to pay extra if the kita in which your child is enrolled offers specific activites or services, such as sports, organic food or language classes, but these costs are officially limited to 90€ a month. Moreover kitas have to be able to provide free of charge places and you have the right to cancel your suscription to these extra activities with a month notice before the end of the month. The EKT (of which we will talk later about) are the only kitas that are an exception to this rule.</p>
    <p>The Gutschein are provided by the <i>Jugendamt</i>, which will ask from parents their need of day care. However, <strong>if the child is at least 1 year old, a Teilzeit Gutschein (5 to 7 hours a day) will be provided regardless of the parents' professional situation</strong>. Moreover, having access to day care passed the age of 1 is officially a right and legal actions can be pushed forward if the parents have not managed to find a spot.</p>
    <p>To apply for a Gutschein, you will have to <strong>go to the Jugendamt of your residential district</strong>. It can be asked for at the earliest 9 months before the desired start of care or 2 months after at the latest. You can also apply online for your Kita Gutschein through this <%= link_to "online formular", "https://fms.verwalt-berlin.de/kita/frm/main?execution=e1s2", target:"_blank", class:"pib-text-link" %></p>

    <h2>How to contact a kita</h2>
    <p>Getting in touch with kitas can prove difficult and time-consuming. This is all the more true that <strong>each has a different approach to the process</strong>. Some will want you to join a collective visit of their facilies right from the start, others will only offer you a visit much later on. Some claim they prefer parents to come directly to the kita to introduce themselves (check the kita website for <i>Sprechzeiten</i>, which is the opening times for meeting and talking with parents), others don't want to be disturbed and prefer parents calling them or sending them an email. Finally, there are some kitas that will accept to put unborn children on their waiting lists and others that don't.</p>
    <p>There is sadly no proper guideline about the best way to get on a kita's waiting list. You will have to contact them each individually and check what is their policy regarding the process. Once you're on a waiting list, <strong>don't forget to call them every 2 months</strong> to remind them of your interest. Indeed, many parents put their child simultaneously on numerous waiting lists and tend not to warn the other kitas once they've been accepted to one. Make sure your kitas do not think you're one of these parents and erase you from their lists after not hearing from you in a while.</p>

    <h2>Other types of children day care</h2>
    <p>Even if kitas are the most typical type of day care, finding a spot can be complicated, but alternatives exist.</p>
    <p>The <strong><i>Tagesmütter</i> or <i>Tageseltern</i> (German equivalent to nannies)</strong> can take care of around 3 to 5 children at a time. Sometimes they pair up to be able to look after 6 to 10 kids. They accept children from a young age, but do not look after children older than 3 - parents will then need to find a kita for the remaining years before school.</p>
    <p>The <strong><i>EKT - Eltern Initiativ Kindertagesstätte</i> are kitas that are run collectively by parents and carers</strong>. They can also be referred to as <i>Kinderladen</i>. They are not as big as kitas, which can be beneficial to the children, and parents have a certain control over the way the kita operates. But they do require some extra time from the parents (cleaning the premises, preparing lunch) and tend to have shorter opening hours. They are not recommended for families where both parents work full-time.</p>

    <div class="box-pib">
      <h3>Going further</h3>
      <p>Here are some links to the city official website:</p>
      <ul class="list-pib list-arrow">
        <li><%= link_to "Kostenbeteiligung und Zuzahlungen", "https://www.berlin.de/sen/jugend/familie-und-kinder/kindertagesbetreuung/kostenbeteiligung/", target:"_blank", class:"pib-text-link" %></li>
        <li><%= link_to "Anmeldung zur Kindertagesbetreuung", "https://www.berlin.de/sen/jugend/familie-und-kinder/kindertagesbetreuung/anmeldung/", target:"_blank", class:"pib-text-link" %></li>
        <li><%= link_to "Kita Gutschein Details und Online-Antrag", "https://fms.verwalt-berlin.de/kita/frm/main?execution=e1s2", target:"_blank", class:"pib-text-link" %></li>
      </ul>
    </div>


  </div>
</div>

app/views/pages/lexicon.html.erb
<% content_for :meta_title, "Lexicon - #{DEFAULT_META["meta_product_name"]}" %>

<div class="container">
  <div class="static-container pages-container">
    <h1>Lexicon</h1>
    <ul class="list-pib list-arrow">
      <li><%= link_to "Kindergartens / Kitas", kitas_path, class:'pib-text-link' %></li>
      <li><%= link_to "Midwives / Hebammen", midwife_system_path, class:'pib-text-link' %></li>
      <li><%= link_to "Paternity Acknowledgment / Vaterschaftanerkennung", paternity_acknowledgment_path, class:'pib-text-link' %></li>
    </ul>
  </div>
</div>

app/views/pages/midwives.html.erb
<% content_for :meta_title, "Midwife system - #{DEFAULT_META["meta_product_name"]}" %>

<div class="container">
  <div class="static-container pages-container">
    <h1>The Midwife System in Germany</h1>
    <h2>What is a midwife?</h2>
    <p>The midwife (<i>Hebamme</i> in German) plays a very important role during the pregnancy, birth and afterwards. They are <strong>trained professionals that will assist you at each step</strong> and their care is reimbursed by the German health insurance.</p>
    <p>Midwives are extremely helpful as they will follow you during your pregnancy and can answer all the questions you have regarding any issues you currently have - may they be food restrictions, back problems etc. They will also guide you and help you make a decision between the different birth options that are available: do you want to give birth at home? at the hospital? or at a <i>Geburtshaus</i>? Many of them offer prenatal courses for couples that ensure a nice preparation to the birth and what comes next for both parents.</p>
    <p>Midwives are <strong>always present during the birth</strong>, no matter where you decide to have your baby. They will monitor you and your baby and will make sure that everything goes well. Afterwards, they will also assist you for the child care and breast-feeding as well as basic medical follow-up for you and your baby (she will for instance make sure that your baby gains back its weight).</p>

    <h2>What is a Geburtshaus?</h2>
    <p>A <i>Geburtshaus</i> (literally, a birth house) is a place where you can give a natural birth. It is meant for <strong>women that would rather have a non-medical birth</strong>, surrounded only by midwives.</p>
    <p>It is important to note that a Geburtshaus will not accept to have your baby delivered in their facilities if your pregnancy falls under the "at risk" category - for instance in the case of multiple births. This is precisely due to the fact that no doctors are present and won't be able to take over right away in case of an emergency.</p>
    <p>It is a very good alternative to giving birth at home and you are well surrounded by trained midwives. If you choose this option, you will need to find one as soon as possible, as the current baby boom in Berlin means that there are less spots available in such places.</p>

    <h2>How to find a midwife?</h2>
    <p>Since midwives play such an important role during and after the pregnancy, their care is very much sought for and it can be actually pretty hard to find one. It is recommended to start looking for one as soon as you have visited your gynecologist.</p>
    <p class="box-pib px-3 py-2"><i>Pregnant in Berlin</i> is currently working on a map that will display all the midwives located around you.</p>
  </div>
</div>

app/views/pages/paternity_acknowledgment.html.erb
<% content_for :meta_title, "Paternity acknowledgment - #{DEFAULT_META["meta_product_name"]}" %>

<div class="container">
  <div class="static-container pages-container">
    <h1>Paternity acknowledgment</h1>

    <h2>In which case is it necessary?</h2>
    <p>In Germany, the law concerning paternity is pretty easy: the mother's husband is the baby's father. Acknowledging paternity and claiming shared custody over the child as a father only need to be done if the baby's parents aren't married, or if the mother's husband isn't the baby's father.</p>
    <p>Acknowledging paternity - or <i>Vaterschatsanerkennung</i> - also <strong>requires the mother to be present</strong> as she needs to consent in front of the commissioner to the acknowledgment of paternity. You can do both the <i>Vaterschatsanerkennung</i> and the <i>Beurkundung der Ausübung der gemeinsamen elterlichen Sorge</i> (registration of shared custody) in one sitting. As both parents have to be present, it is strongly recommended to <strong>do both declarations before the child is born</strong> as you might not have as much free time once your baby is there! On a more practical aspect of doing so before the birth, the child can only have its father's family name if the father acknowledged his paternity, thus being an extra reason to do the declaration before the birth.</p>

    <h2>Where to go? What to bring?</h2>
    <p>Both declarations can be done together at the <i>Jugendamt</i> (youth welfare office) free of charge. You must <strong>get an appointment at the Jugendamt of the mother's residence</strong>. However most of Berlin's administration offices are aware of the long delays to get an appointment and can be understanding of your situation, so do feel free to contact other Jugendämter in case the one you officially depend on doesn't have any availibilities that fit you. You can also potentially do it at a notary, but the costs can be high.</p>
    <p>Once you have your appointment, they will ask you to <strong>send copies of all the following documents per post or email</strong>. You will need to bring the original documents along the day of your appointment.</p>
    <ul class="list-pib list-tick">
      <li><span class="font-dark-blue font-weight-bold font-weight-bold">ID of both parents</span></li>
      <li><span class="font-dark-blue font-weight-bold">Birth certificates of both parents</span> - if the birth certificates were delivered in another country, they shall be officially translated beforehand. Noteworthy: if you are from a EU land, some civil registry offices actually offer multi-lingual birth certificates.</li>
      <li><span class="font-dark-blue"><i>If the name on the birth certificate isn't the name as the one on your ID:</i></span> bring along a justification, for instance the <span class="font-dark-blue font-weight-bold">certificate of name change or the marriage certificate</span>.</li>
      <li><span class="font-dark-blue font-weight-bold">Mutterpass or birth certificate of the child</span> if already born</li>
      <li><span class="font-dark-blue"><i>In case one or both parents do not speak sufficient German:</i></span> you will need to bring along an <span class="font-dark-blue font-weight-bold">interpreter that isn't related to any of the parents</span>. The interpreter shall have a valid ID.</li>
    </ul>

    <div class="box-pib">
      <h3>Going further</h3>
      <p>Here are the links to the official Berlin portal:</p>
      <ul class="list-pib list-arrow">
        <li><%= link_to "Paternity acknowledgment", "https://service.berlin.de/dienstleistung/318991/", target:"_blank", class:"pib-text-link" %></li>
        <li><%= link_to "Shared common custody", "https://service.berlin.de/dienstleistung/326590/", target:"_blank", class:"pib-text-link" %></li>
      </ul>
    </div>

  </div>
</div>